### ISSUE TITLE
Include historic (pre-API) data as dataset?

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmetr#11]
The API currently doesn't have data before 2020-12-30.  Could we include the historic data as a dataset in the R package?

**Comment by jeremylweiss** [comment]
AZMet data pre-2021 are available online as annual text files (hourly and daily, separate files) by station and by year:

https://cals.arizona.edu/azmet/az-data.htm

They are a totally different animal, format-wise. By ‘include in the R package’, do you mean to have the package also able to download and transform these files to a format that matches the one of the corresponding API data table?


From: Eric R. Scott ***@***.***>
Date: Monday, October 10, 2022 at 11:31 AM
To: cct-datascience/azmetr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT][cct-datascience/azmetr] Include historic (pre-API) data as dataset? (Issue #11)

External Email

The API currently doesn't have data before 2020-12-30. Could we include the historic data as a dataset in the R package?

**Comment by Aariq** [comment]
I was thinking they could just be included as a static dataset.  Just like the `diamonds` dataset that comes with `ggplot2` or the `starwars` dataset that comes with `dplyr`

**Comment by jeremylweiss** [comment]
A daily file for a given year and station is ~ 45 kb, an hourly file is ~620 kb. Going through the station lineup, there are 651 total stations years for currently active stations, and 167 total station years for currently inactive stations. That makes for ~433 MB of active station data and ~111 MB of inactive station data.

Would that be too much to saddle an R package with?



From: Eric R. Scott ***@***.***>
Date: Friday, October 14, 2022 at 10:13 AM
To: cct-datascience/azmetr ***@***.***>
Cc: Weiss, Jeremy - (jlweiss) ***@***.***>, Comment ***@***.***>
Subject: [EXT]Re: [cct-datascience/azmetr] Include historic (pre-API) data as dataset? (Issue #11)

External Email

I was thinking they could just be included as a static dataset. Just like the diamonds dataset that comes with ggplot2 or the starwars dataset that comes with dplyr
