### ISSUE TITLE
Hex logo

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmetr#20]
Gotta have a hex logo for the package, right?

**Comment by jeremylweiss** [comment]
Craig B. at CCT has put together a bunch of icons that we're using on the new AZMet website (under construction). Maybe the station one here: https://staging.azmet.arizona.edu/past-data/station-level-summaries ?

**Comment by dlebauer** [comment]
Maybe put the icon inside an outline of the state?

**Comment by jeremylweiss** [comment]
Got one of those, too: https://staging.azmet.arizona.edu/past-data/network-wide-summary

**Comment by dlebauer** [comment]
![Picture6](https://user-images.githubusercontent.com/464871/206768957-e19a6054-0a70-4f34-8fd7-b83432c156cb.png)
???

**Comment by jeremylweiss** [comment]
I imagine we could ask Craig B. at CCT to combine the two

**Comment by Aariq** [comment]
Looks nice, maybe put the package name in there somewhere too? Maybe some dots representing the active stations?

**Comment by Aariq** [comment]
``` r
library(azmetr)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(maps)
az <- map_data("state", "arizona")
ggplot() + 
  geom_polygon(data = az, aes(x = long, y = lat, group = group), color = "black", fill =  "lightblue") +
  geom_point(data = station_info, aes(x = longitude, y = latitude)) +
  coord_map() +
  theme_void()
```

![](https://i.imgur.com/ogWfhUU.png)

<sup>Created on 2022-12-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jeremylweiss** [comment]
![az-weatherstation](https://github.com/uace-azmet/azmetr/assets/17934972/55f02598-f520-4623-9544-c04909a15036)

**Comment by Aariq** [comment]
Very nice!  You can use `usethis::use_logo()` to add it to the package

**Comment by KristinaRiemer** [comment]
This logo looks great!
