### ISSUE TITLE
Allow more flexibility in start and end datetimes for `az_hourly()`

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmetr#44]
The following inputs currently error, but it would be cool if they worked in some way:

``` r
library(azmetr)
az_hourly(start_date_time = "2023-07-11")
#> Error: `start_date` failed to parse
az_hourly(start_date_time = as.POSIXct("2023-07-11"))
#> Error: `start_date` failed to parse
az_hourly(start_date_time = as.Date("2023-07-11"))
#> Error: `start_date` failed to parse
```

<sup>Created on 2023-07-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If these arguments could accept any level of precision (e.g. by rounding down) then it might be good to deprecate `start_date_time` and `end_date_time` (and the equivalents in `az_daily()`) and replace with just `start` and `end`

**Comment by Aariq** [comment]
Check if vignette can be simplified if and when this change is made

**Comment by Aariq** [comment]
@jeremylweiss if you could run `az_hourly(start = "2023-10-01", end = "2023-10-02")` what would you expect to get?

A) 24 readings, one for every hour on the 1st from 01:00:00 to 23:59:59 (ending just before the 2nd)
B) 48 readings going through the _end_ of the 2nd (last data point on 2023-10-02 23:59:59)

**Comment by jeremylweiss** [comment]
Friday quiz! I choose 'B'. With the added detail that what comes back has a first data point of 2023-10-01 01:00:00
