### ISSUE TITLE
Timestamps for midnight coded as 23:59:59 rather than 00:00:00

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmetr#53]
Hourly data is not "perceived" as hourly if converted to a timeseries (e.g. by `tsibble::as_tsibble()`) because midnight is coded as 23:59:59.  Not sure if this is a change that should be made in the API, but for now it can be made in `azmetr` by rounding those dates up.

``` r
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
x <- c("2023-01-01 23:00:00", "2023-01-01 23:59:59" , "2023-01-02 01:00:00")
ymd_hms(x) |> ceiling_date("hour")
#> [1] "2023-01-01 23:00:00 UTC" "2023-01-02 00:00:00 UTC"
#> [3] "2023-01-02 01:00:00 UTC"
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Aariq** [comment]
For context, my approach for detecting non-reporting stations has been to convert to a `tsibble` and use functions like `has_gaps()` and `count_gaps()` to identify missing dates or timestamps. This doesn't work for hourly since `as_tsibble()` thinks the interval of the timeseries is **seconds** and therefore there are a _LOT_ of missing seconds!

**Comment by jeremylweiss** [comment]
I recall Matt Harmon noting that a date with time `00:00` is somehow not agreeable with the database setup and/or code. The `23:59:59` hour value is the solution to that technical issue. In reality, the station dataloggers record at `00:00`.

The `ceiling_date("hour")` solution above cleans this up. However, the `00:00` hour is set to `date + 1`, even though the values at that date-time represent data from `date`, which makes for confusion if filtering by dates. Perhaps this is the issue Matt Harmon ran up against.

**Comment by Aariq** [comment]
Ah, I see now.  `date_doy` and `date_hour` no longer match because exactly midnight falls at the start of the day, not the end (at least in R). Well, I see a few options:

1. Leave things as-is in `azmetr` (23:59:59) and deal with the rounding up to midnight only in the QA dashboard (i.e., this doesn't need fixing)
2. Also adjust the `date_doy` and `date_hour` to match
3. Just remove `date_doy` and `date_hour` columns from what is returned by `az_hourly()` since that info can be extracted from `date_datetime` (e.g. `lubridate::yday(date_datetime)` for DOY)

**Comment by Aariq** [comment]
Decided to leave as is
