### ISSUE TITLE
unknown timezone warning with `az_15min()` and `az_lw15min()`

### ISSUE THREAD

**Issue by jeremylweiss** [uace-azmet/azmetr#78]
Use of `az_15min()` and `az_lw15min()` functions with `start_date_time` parameter set results in the warning message `In as.POSIXlt.POSIXct(x, tz) : unknown timezone ' ...'`

```r
az_15min(start_date_time = lubridate::today(tzone = "America/Phoenix"))
```
```r
az_lw15min(start_date_time = lubridate::today(tzone = "America/Phoenix"))
```

**Comment by Aariq** [comment]
I think I spotted the source of this one.  I'll make a PR.
